server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # todo  是否可以配置私有库的访问账号密码
          uri: https://github.com/springcloud-will/springcloud-config.git
          search-paths:
            - springcloud-config
          default-label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-center3344
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


