server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: hystrix-order80
    prefer-ip-address: true

feign:
  httpclient:
    enabled: true
    connection-timeout: 1000000
    connection-timer-repeat: 10000
logging:
  level:
    com.george.springcloud.service: info