server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  type-aliases-package: com.atme.springcloud.entities
  mapper-locations: classpath:mapper/*.xml


